version: "3.9"

services:
  db:
    image: mariadb:11
    container_name: falcon_database
    environment:
      - MARIADB_ROOT_PASSWORD={MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE={MARIADB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    container_name: falcon_api
    build:
        context: .
        dockerfile: /Dockerfile
    ports:
    - "8080:8080"
    - "80:80"
    - "443:443"
    - "7163:7163"
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ConnectionStrings__DefaultConnection=server=db;user=root;password={MARIADB_ROOT_PASSWORD};database={MARIADB_DATABASE}
    
    depends_on:
      db:
        condition: service_healthy
    env_file: .env.development
volumes:
  db_data:
